/*
 * generated by Xtext 2.13.0
 */
package org.framed.iorm.editpolicydsl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class DslAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/framed/iorm/editpolicydsl/parser/antlr/internal/InternalDsl.tokens");
	}
}
