/**
 * generated by Xtext 2.13.0
 */
package org.framed.iorm.editpolicydsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.framed.iorm.editpolicydsl.ui.AbstractDslUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class DslUiModule extends AbstractDslUiModule {
  public DslUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
