/*
 * generated by Xtext 2.13.0
 */
package org.framed.iorm.editpolicydsl.formatting2

import com.google.inject.Inject
import org.eclipse.xtext.formatting2.AbstractFormatter2
import org.framed.iorm.editpolicydsl.services.DslGrammarAccess

class DslFormatter extends AbstractFormatter2 {
	
	@Inject extension DslGrammarAccess
	
	// TODO: implement for 
}
