/*
 * generated by Xtext 2.13.0
 */
package org.framed.iorm.editpolicydsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractDslScopeProvider extends DelegatingScopeProvider {
}
