/**
 * generated by Xtext 2.13.0
 */
package org.framed.iorm.editpolicydsl.validation;

import org.framed.iorm.editpolicydsl.validation.AbstractDslValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class DslValidator extends AbstractDslValidator {
}
