/**
 * generated by Xtext 2.13.0
 */
package org.framed.iorm.editpolicydsl.formatting2;

import com.google.inject.Inject;
import org.eclipse.xtext.formatting2.AbstractFormatter2;
import org.eclipse.xtext.formatting2.IFormattableDocument;
import org.eclipse.xtext.xbase.lib.Extension;
import org.framed.iorm.editpolicydsl.services.DslGrammarAccess;

@SuppressWarnings("all")
public class DslFormatter extends AbstractFormatter2 {
  @Inject
  @Extension
  private DslGrammarAccess _dslGrammarAccess;
  
  @Override
  public void format(final Object obj, final IFormattableDocument document) {
    throw new UnsupportedOperationException("TODO: auto-generated method stub");
  }
}
