<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="Editpolicymodel" nsURI="http://www.example.org/editpolicymodel"
    nsPrefix="Editpolicymodel">
  <eClassifiers xsi:type="ecore:EClass" name="Model">
    <eStructuralFeatures xsi:type="ecore:EReference" name="policy" upperBound="-1"
        eType="#//Policy" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Policy">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="override" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="action" eType="#//ActionEnum"
        defaultValueLiteral="Create"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ActionType" eType="ecore:EEnum ../../org.framed.iorm.model/model/IORM.ecore#//Type"
        defaultValueLiteral="CompartmentType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="featureRule" containment="true">
      <eGenericType eClassifier="#//AbstractRule">
        <eTypeArguments eClassifier="#//Feature"/>
      </eGenericType>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="constraintRule" containment="true">
      <eGenericType eClassifier="#//AbstractRule">
        <eTypeArguments eClassifier="#//Constraint"/>
      </eGenericType>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Contains" eSuperTypes="#//Constraint"/>
  <eClassifiers xsi:type="ecore:EClass" name="IsStepOut" eSuperTypes="#//Constraint"/>
  <eClassifiers xsi:type="ecore:EClass" name="IsTargetConstraintRule" eSuperTypes="#//Constraint"/>
  <eClassifiers xsi:type="ecore:EClass" name="IsSourceConstraintRule" eSuperTypes="#//Constraint"/>
  <eClassifiers xsi:type="ecore:EClass" name="IsParentConstraintRule" eSuperTypes="#//Constraint"/>
  <eClassifiers xsi:type="ecore:EEnum" name="ActionEnum">
    <eLiterals name="Create"/>
    <eLiterals name="Add" value="1"/>
    <eLiterals name="Start" value="2"/>
    <eLiterals name="Reconnect" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractRule" abstract="true" interface="true">
    <eTypeParameters name="T"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Rule" eSuperTypes="#//AbstractRule">
    <eTypeParameters name="T"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rule" containment="true">
      <eGenericType eTypeParameter="#//Rule/T"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Feature" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="IsFeature" eSuperTypes="#//Feature"/>
  <eClassifiers xsi:type="ecore:EClass" name="Constraint" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="IsTargetType" eSuperTypes="#//Constraint"/>
  <eClassifiers xsi:type="ecore:EClass" name="UnaryRule" abstract="true" eSuperTypes="#//AbstractRule">
    <eTypeParameters name="T"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rule" containment="true">
      <eGenericType eClassifier="#//AbstractRule">
        <eTypeArguments eTypeParameter="#//UnaryRule/T"/>
      </eGenericType>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NotRule" eSuperTypes="#//UnaryRule"/>
  <eClassifiers xsi:type="ecore:EClass" name="AndRule" eSuperTypes="#//BinaryRule"/>
  <eClassifiers xsi:type="ecore:EClass" name="BinaryRule" abstract="true" eSuperTypes="#//AbstractRule">
    <eTypeParameters name="T"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="leftRule" containment="true">
      <eGenericType eClassifier="#//AbstractRule">
        <eTypeArguments eTypeParameter="#//BinaryRule/T"/>
      </eGenericType>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rightRule" containment="true">
      <eGenericType eClassifier="#//AbstractRule">
        <eTypeArguments eTypeParameter="#//BinaryRule/T"/>
      </eGenericType>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TrueRule" eSuperTypes="#//AbstractRule"/>
  <eClassifiers xsi:type="ecore:EClass" name="FalseRule" eSuperTypes="#//AbstractRule"/>
  <eClassifiers xsi:type="ecore:EClass" name="OrRule" eSuperTypes="#//BinaryRule"/>
  <eClassifiers xsi:type="ecore:EClass" name="ImplicationRule" eSuperTypes="#//BinaryRule"/>
</ecore:EPackage>
