<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="Editpolicymodel" nsURI="http://framed/editpolicymodel" nsPrefix="Editpolicymodel">
  <eClassifiers xsi:type="ecore:EClass" name="Model">
    <eStructuralFeatures xsi:type="ecore:EReference" name="policies" upperBound="-1"
        eType="#//Policy" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Policy">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="override" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="action" eType="#//ActionEnum"
        defaultValueLiteral="Create"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="actionType" eType="ecore:EEnum ../../org.framed.iorm.model/model/IORM.ecore#//Type"
        defaultValueLiteral="CompartmentType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="featureRule" eType="#//FeatureRule"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="constraintRule" eType="#//ConstraintRule"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Contains" eSuperTypes="#//TypeArgumentRule"/>
  <eClassifiers xsi:type="ecore:EClass" name="IsStepIn" eSuperTypes="#//ConstraintRule"/>
  <eClassifiers xsi:type="ecore:EClass" name="IsTarget" eSuperTypes="#//TypeArgumentRule"/>
  <eClassifiers xsi:type="ecore:EClass" name="IsSource" eSuperTypes="#//TypeArgumentRule"/>
  <eClassifiers xsi:type="ecore:EClass" name="IsParent" eSuperTypes="#//TypeArgumentRule"/>
  <eClassifiers xsi:type="ecore:EEnum" name="ActionEnum">
    <eLiterals name="Create"/>
    <eLiterals name="Add" value="1"/>
    <eLiterals name="Start" value="2"/>
    <eLiterals name="Reconnect" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FeatureRule" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="IsFeature" eSuperTypes="#//FeatureRule">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="featureName" eType="ecore:EEnum ../../org.framed.iorm.model/model/IORM.ecore#//featuremodel/FeatureName"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConstraintRule" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="IsTargetType" eSuperTypes="#//TypeArgumentRule"/>
  <eClassifiers xsi:type="ecore:EClass" name="UnaryConstraintRule" abstract="true"
      eSuperTypes="#//LogicalConstraintRule">
    <eStructuralFeatures xsi:type="ecore:EReference" name="rule" lowerBound="1" eType="#//ConstraintRule"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NotConstraintRule" eSuperTypes="#//UnaryConstraintRule"/>
  <eClassifiers xsi:type="ecore:EClass" name="AndConstraintRule" eSuperTypes="#//NaryConstraintRule"/>
  <eClassifiers xsi:type="ecore:EClass" name="BinaryConstraintRule" abstract="true"
      eSuperTypes="#//LogicalConstraintRule">
    <eStructuralFeatures xsi:type="ecore:EReference" name="leftRule" lowerBound="1"
        eType="#//ConstraintRule" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rightRule" lowerBound="1"
        eType="#//ConstraintRule" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TrueConstraintRule" eSuperTypes="#//LogicalConstraintRule"/>
  <eClassifiers xsi:type="ecore:EClass" name="FalseConstraintRule" eSuperTypes="#//LogicalConstraintRule"/>
  <eClassifiers xsi:type="ecore:EClass" name="OrConstraintRule" eSuperTypes="#//NaryConstraintRule"/>
  <eClassifiers xsi:type="ecore:EClass" name="ImplicationConstraintRule" eSuperTypes="#//BinaryConstraintRule"/>
  <eClassifiers xsi:type="ecore:EClass" name="IsSourceType" eSuperTypes="#//TypeArgumentRule"/>
  <eClassifiers xsi:type="ecore:EClass" name="TypeArgumentRule" abstract="true" eSuperTypes="#//ConstraintRule">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EEnum ../../org.framed.iorm.model/model/IORM.ecore#//Type"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NaryConstraintRule" abstract="true"
      eSuperTypes="#//LogicalConstraintRule">
    <eStructuralFeatures xsi:type="ecore:EReference" name="rules" lowerBound="1" upperBound="-1"
        eType="#//ConstraintRule" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LogicalConstraintRule" eSuperTypes="#//ConstraintRule"/>
  <eClassifiers xsi:type="ecore:EClass" name="TrueFeatureRule" eSuperTypes="#//LogicalFeatureRule"/>
  <eClassifiers xsi:type="ecore:EClass" name="NotFeatureRule" eSuperTypes="#//UnaryFeatureRule"/>
  <eClassifiers xsi:type="ecore:EClass" name="FalseFeatureRule" eSuperTypes="#//LogicalFeatureRule"/>
  <eClassifiers xsi:type="ecore:EClass" name="NaryFeatureRule" abstract="true" eSuperTypes="#//LogicalFeatureRule">
    <eStructuralFeatures xsi:type="ecore:EReference" name="rules" upperBound="-1"
        eType="#//FeatureRule" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BinaryFeatureRule" abstract="true" eSuperTypes="#//LogicalFeatureRule">
    <eStructuralFeatures xsi:type="ecore:EReference" name="rightRule" lowerBound="1"
        eType="#//FeatureRule" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="leftRule" lowerBound="1"
        eType="#//FeatureRule" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LogicalFeatureRule" eSuperTypes="#//FeatureRule"/>
  <eClassifiers xsi:type="ecore:EClass" name="ImplicationFeatureRule" eSuperTypes="#//BinaryFeatureRule"/>
  <eClassifiers xsi:type="ecore:EClass" name="UnaryFeatureRule" abstract="true" eSuperTypes="#//LogicalFeatureRule">
    <eStructuralFeatures xsi:type="ecore:EReference" name="rule" lowerBound="1" eType="#//FeatureRule"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OrFeatureRule" eSuperTypes="#//NaryFeatureRule"/>
  <eClassifiers xsi:type="ecore:EClass" name="AndFeatureRule" eSuperTypes="#//NaryFeatureRule"/>
</ecore:EPackage>
