/**
 * generated by Xtext 2.13.0
 */
package org.framed.iorm.editpolicydsl.ide;

import org.framed.iorm.editpolicydsl.ide.AbstractDslIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class DslIdeModule extends AbstractDslIdeModule {
}
