/*
 * generated by Xtext 2.13.0
 */
package org.framed.iorm.editpolicydsl

import org.eclipse.xtext.conversion.IValueConverterService

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class DslRuntimeModule extends AbstractDslRuntimeModule {
	
	override Class<? extends IValueConverterService> bindIValueConverterService() {
    	return MyValueConverter;
	}
}
